<#
.SYNOPSIS
Simulate excessive file access via Windows Object Access audit Events.

.DESCRIPTION
Takes two arguments: -impactedUser & -serverName

.EXAMPLE
./C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe -file Ransomware-ExcessiveFileAccess.ps1 -impactedUser "Charles.Lindbergh" -serverName "LRXM"

.NOTES
April 2017 @chrismartin

.LINK
https://github.com/lrchma/Use-Case-Scripts

#>

param(
  [Parameter(Mandatory=$false)]
  [string]$impactedUser = 'charles.lindbergh',
  [Parameter(Mandatory=$false)]
  [string]$serverName = 'lrxm'
)

#Dot Source Variables - scripts need have the working directory as this path or they'll fail
. .\variables.ps1

#Windows date format, e.g. 2017-04-11T17:06:16
$date = Get-Date -format s

#prefix for log file, this is used in flat file path wildcard, suggest this not be changed.
$prefix = "winsec"

[string]$random = get-random
$outputfile = $path + $prefix + $random + $extension

$logs = @(" ",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file1.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file2.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file3.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file4.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file5.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file6.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file7.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file8.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file9.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file10.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file11.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file12.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file13.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file14.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file15.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file16.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file17.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file18.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file19.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file20.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file21.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file22.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file23.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file24.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file25.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file26.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file27.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file28.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file29.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file30.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file31.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>",
"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4663</EventID><Version>0</Version><Level>Information</Level><Task>File System</Task><Opcode>Info</Opcode><Keywords>Audit Success</Keywords><TimeCreated SystemTime=$date.123456789Z'/><EventRecordID>86613270</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='72'/><Channel>Security</Channel><Computer>$servername</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>$servername\$impacteduser</Data><Data Name='SubjectUserName'>$impacteduser</Data><Data Name='SubjectDomainName'>$servername</Data><Data Name='SubjectLogonId'>0x3cc6fd53a</Data><Data Name='ObjectServer'>Security</Data><Data Name='ObjectType'>File</Data><Data Name='ObjectName'>C:\Users\$impacteduser\AppData\Roaming\file32.txt</Data><Data Name='HandleId'>0x68</Data><Data Name='AccessList'>%%4416</Data><Data Name='AccessMask'>0x1</Data><Data Name='ProcessId'>0x300c</Data><Data Name='ProcessName'>C:\Users\$impacteduser\AppData\Roaming\7zbcda.exe</Data></EventData></Event>"
)



try {
    Foreach($log in $logs)
        {
           $log | Add-Content $outputfile
        }
    }catch{
       $ErrorMessage = $_.Exception.Message
       write-host $ErrorMessage   
    }





